on:
  push:
    branches:
      - main
  pull_request:
  
name: PR - Crawl Docs for broken links

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: docs/**/*.md
          markdown: true
          linksToSkip: ^(?!https:\/\/)
          
