name: Slinky - Crawl Docs for broken links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: 'slinky'
  cancel-in-progress: true

jobs:
  slinky:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: LukeHagar/slinky@v1
          
